Project.create!(name: "Complete the test task for Ruby Garage")

Task.create!(name: "I want to be able to create/update/delete projects ", status: true, project_id: 1)
Task.create!(name: "I want to be able to add tasks to my project", status: true, project_id: 1)
Task.create!(name: "I want to be able to update/delete tasks", status: true, project_id: 1)
Task.create!(name: "I want to be able to prioritise tasks into a project", status: true, project_id: 1)
Task.create!(name: "I want to be able to choose deadline for my task", status: false, project_id: 1)
Task.create!(name: "I want to be able to mark a task as 'done'", status: true, project_id: 1)
Task.create!(name: "It should be WEB application: For the client  HTML, CSS (Twitter Bootstrap), JavaScript (jQuery, Backbone); For server side : Ruby", status: true, project_id: 1)
Task.create!(name: "It should have client side and server side validation", status: false, project_id: 1)
Task.create!(name: "It should look like on screens (see attached file rg_test_task_grid.png)", status: true, project_id: 1)
Task.create!(name: "It should work like one page WEB application and should use AJAX technology, load and submit data without reloading a page.", status: true, project_id: 1)
Task.create!(name: "It should have user authentication solution and a user should only have access to their own projects and tasks.", status: false, project_id: 1)
Task.create!(name: "It should have automated tests for all functionality", status: false, project_id: 1)
